import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { flex_css } from '../shared/styles/shared'
import Category from '../src/product_list/components/Category'
import List from '../src/product_list/components/List'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={flex_css.flex_row}>
        <Category />
        <List />
      </main>
    </div>
  )
}

export default Home
